// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmumEnRWtwJtxiVTsTzl1kSJ7hs2DSV_4',
    appId: '1:740536503318:web:64cc65fd774a028d63b937',
    messagingSenderId: '740536503318',
    projectId: 'capacious-74ab4',
    authDomain: 'capacious-74ab4.firebaseapp.com',
    storageBucket: 'capacious-74ab4.appspot.com',
    measurementId: 'G-V9MKF4KN1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHgNkujqQmkMnSMni4T_-f0WNpPenTBkI',
    appId: '1:740536503318:android:6710c1df58e97d1e63b937',
    messagingSenderId: '740536503318',
    projectId: 'capacious-74ab4',
    storageBucket: 'capacious-74ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsKeueudqoxiVmv1g-hNl0M3ce2DNh0IA',
    appId: '1:740536503318:ios:0db5c7fe1426c27363b937',
    messagingSenderId: '740536503318',
    projectId: 'capacious-74ab4',
    storageBucket: 'capacious-74ab4.appspot.com',
    iosClientId:
        '740536503318-f2ofr5guf61vpsqgf2r24ule3isr7c6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.capacious',
  );
}
